
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/librarie_db
quarkus.datasource.username=postgres
quarkus.datasource.password=1q2w3e


quarkus.hibernate-orm.database.generation=update